[package]
name = "dlms_cosem_rs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.dlms_cosem_rs]
path = ".."
features = ["std", "client", "server", "hdlc", "wrapper", "p1", "suite0"]

[[bin]]
name = "data"
path = "fuzz_targets/data.rs"
test = false
doc = false

[[bin]]
name = "apdu"
path = "fuzz_targets/apdu.rs"
test = false
doc = false

[[bin]]
name = "acse"
path = "fuzz_targets/acse.rs"
test = false
doc = false

[[bin]]
name = "hdlc"
path = "fuzz_targets/hdlc.rs"
test = false
doc = false

[[bin]]
name = "wrapper"
path = "fuzz_targets/wrapper.rs"
test = false
doc = false

[[bin]]
name = "notification"
path = "fuzz_targets/notification.rs"
test = false
doc = false

[[bin]]
name = "server_session"
path = "fuzz_targets/server_session.rs"
test = false
doc = false

[[bin]]
name = "gbt"
path = "fuzz_targets/gbt.rs"
test = false
doc = false

[[bin]]
name = "p1"
path = "fuzz_targets/p1.rs"
test = false
doc = false
